name: CI_Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build & Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux-x86_64-musl, linux-x86_64-gnu, macos-x86_64, windows-x86_64-msvc, windows-x86_64-gnu]
        include:
          - build: linux-x86_64-musl
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-musl
            archive-name: nginx-spcgen-linux-x86_64-musl.tar.gz
          - build: linux-x86_64-gnu
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
            archive-name: nginx-spcgen-linux-aarch64-gnu.tar.gz
          - build: macos-x86_64
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
            archive-name: nginx-spcgen-darwin-x86_64.tar.gz
          - build: windows-x86_64-msvc
            os: windows-latest
            rust: stable-x86_64-msvc
            target: x86_64-pc-windows-msvc
            archive-name: nginx-spcgen-windows-x86_64-msvc.7z
          - build: windows-x86_64-gnu
            os: windows-latest
            rust: stable-x86_64-gnu
            target: x86_64-pc-windows-gnu
            archive-name: nginx-spcgen-windows-x86_64-gnu.7z
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --verbose --release --target ${{ matrix.target }}
        env:
          RUST_BACKTRACE: 1
      
      - name: Strip binary (linux and macos)
        if: matrix.build == 'linux' || matrix.build == 'macos'
        run: strip "target/${{ matrix.target }}/release/nginx_spcgen"

      - name: Build archive
        shell: bash
        run: |
          mkdir archive
          cp LICENSE README.md archive/
          cd archive
          if [ "${{ matrix.build }}" = "windows" ]; then
            cp "../target/${{ matrix.target }}/release/nginx_spcgen.exe" ./
            7z a "${{ matrix.archive-name }}" LICENSE README.md nginx_spcgen.exe
          else
            cp "../target/${{ matrix.target }}/release/nginx_spcgen" ./
            tar -czf "${{ matrix.archive-name }}" LICENSE README.md nginx_spcgen
          fi
      
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.archive-name }}
          path: archive/${{ matrix.archive-name }}
      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          files: archive/${{ matrix.archive-name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}